# Generated by Django 4.1.6 on 2023-02-13 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=3)),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('banner_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.term')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=3)),
                ('abbr', models.CharField(max_length=4)),
                ('crn', models.CharField(max_length=5)),
                ('campus', models.CharField(max_length=2)),
                ('credits', models.CharField(max_length=1)),
                ('days', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=70)),
                ('location', models.CharField(max_length=10)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.term')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.subject'),
        ),
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.term'),
        ),
    ]
