# Generated by Django 4.1.6 on 2023-02-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpringFall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('titles', models.CharField(max_length=3)),
                ('sections', models.CharField(max_length=3)),
                ('CRN', models.CharField(max_length=5)),
                ('campus', models.CharField(max_length=2)),
                ('credits', models.CharField(max_length=1)),
                ('days', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SummerI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('titles', models.CharField(max_length=3)),
                ('sections', models.CharField(max_length=3)),
                ('CRN', models.CharField(max_length=5)),
                ('campus', models.CharField(max_length=2)),
                ('credits', models.CharField(max_length=1)),
                ('days', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SummerII',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjects', models.CharField(max_length=100)),
                ('titles', models.CharField(max_length=3)),
                ('sections', models.CharField(max_length=3)),
                ('CRN', models.CharField(max_length=5)),
                ('campus', models.CharField(max_length=2)),
                ('credits', models.CharField(max_length=1)),
                ('days', models.CharField(max_length=5)),
                ('time', models.CharField(max_length=20)),
                ('instructor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='pin',
            field=models.CharField(max_length=6),
        ),
    ]
