# Generated by Django 4.1.6 on 2023-02-17 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('banner_id', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=6)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('major', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=15)),
                ('classification', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='section',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='section',
            name='term',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='term',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
    ]
