# Generated by Django 4.1.6 on 2023-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_studentinfo_remove_section_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='pin',
            field=models.CharField(max_length=15),
        ),
    ]
